### ISSUE TITLE
Syntax error in reportObjectMapper array_filter callback function (anonymous PHP function)

### ISSUE THREAD

**Issue by forumco** [erebusnz/gapi-google-analytics-php-interface#115]
I have this error message when i load example.report.php :

Parse error: syntax error, unexpected T_FUNCTION in /.../gapi.class.php on line 277

Any idea what is causing this bug ?

**Comment by bundbud** [comment]
I have some error. 

Parse error: syntax error, unexpected T_FUNCTION in /.../gapi.class.php on line 277

Any solution?

**Comment by erebusnz** [comment]
Since v2.0.0 version, minimum PHP requirement is PHP 5.3.0 due to use of anonymous functions.

Currently cannot replicate this error in PHP 5.5.9, 5.5.24 or 5.6.8. Please supply PHP version number if you wish further investigation.

It would be possible to re-write GAPI to work with old versions but not recommended, [PHP does not support versions earlier 5.3 any longer and does not provide security updates](http://php.net/archive/2010.php#id2010-12-16-1).
