### ISSUE TITLE
Parse Error line 277 gapi.class.php

### ISSUE THREAD

**Issue by webferas** [erebusnz/gapi-google-analytics-php-interface#117]
Parse error: syntax error, unexpected T_FUNCTION in /home/public_html/gapi.class.php on line 277

**Comment by erebusnz** [comment]
Since v2.0.0 version, minimum PHP requirement is PHP 5.3.0 due to use of anonymous functions.

It would be possible to re-write GAPI to work with old versions but not recommended, [PHP does not support versions earlier 5.3 any longer and does not provide security updates](http://php.net/archive/2010.php#id2010-12-16-1).

Please upgrade your version of PHP.
