### ISSUE TITLE
Need to specify separator argument to http_build_query to address problem with &amp; default

### ISSUE THREAD

**Issue by dawansv** [erebusnz/gapi-google-analytics-php-interface#118]
This relates to the use of http_build_query in the curlRequest function (line 757 of gapi.class.php)

In some situations, it seems that the default query separtor on a given server is &amp;amp; instead of &.  When http_build_query is called without specifying the separator, the default is used, and if it happens to be &amp;amp; then the request fails.

Simple solution is to specify the separator in the call on line 757 of gapi.class.php:
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post_variables, '', '&'));

**Comment by erebusnz** [comment]
Issue fixed in [commit 3ae92e1458fcec021fba5ea60a1f9a7bdaeb3238](https://github.com/erebusnz/gapi-google-analytics-php-interface/commit/3ae92e1458fcec021fba5ea60a1f9a7bdaeb3238) will be included in next version. Thanks

**Comment by Makcym** [comment]
Hi 
I did all of the new instruction on different sites with PHP 5.3.3, .p12 file exists but

Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed load key file "key.p12". 
Check if correct p12 format.' in YYY.php:603 
Stack trace: 
#0 YYY.php(126): gapiOAuth2->fetchToken('XXX@gmail.com', 'YYY.php', NULL) 
#1 YYY.php(788): gapi->__construct('XXX@gmail.com', 'YYY.php') 
#2 {main} thrown in YYY.php on line 603

**Comment by erebusnz** [comment]
Hi @Makcym,

This issue #118 is relating to a different issue, if you would like to raise this then please create a new issue.

As for your issue, you will need to use a service account, these end in @developer.gserviceaccount.com and need to be created by following these instructions carefully:

GAPI (because now Google Analytics API only supports OAuth2) will require you to create a 'service account' and then download a .P12 file to upload to your application.

  1. Create a [Google Developers project](https://console.developers.google.com/project)
  2. Create service account under this project, [see instructions](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount)
  3. Download the .p12 file for this service account, upload to the same folder as **gapi.class.php**
  4. Enable 'analytics API' in the [Google Developers console]((https://console.developers.google.com/project))
  5. In Google Analytics *Administration > User Management*, give the service account 'Read and Analyse' permissions on the analytics accounts you want to access
