### ISSUE TITLE
Could the php version be an issue ?

### ISSUE THREAD

**Issue by Warface** [erebusnz/gapi-google-analytics-php-interface#130]
I have two servers. One with PHP 5.3.3 and another on 5.5

On the 5.5 version the code runs fine but on the 5.3.3, I always get the 
Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed to authenticate user. Error: "{ "error": "invalid_grant", "error_description": "Bad Request" }

It's the exact same script running on both. Any clue if the PHP version could cause this issue?

**Comment by Warface** [comment]
God damnit!!!!!

Please add this in your doc, assure that your server time is up to date!

Sync the time with 

`ntpdate -s time.nist.gov `

**Comment by erebusnz** [comment]
Thanks @Warface will review documentation

**Comment by akabaka** [comment]
I'm getting the same error and have double- and triple-checked that the server time is synced and correct. Could it be anything else?

**Comment by akabaka** [comment]
So, when I went through all the steps of making the Google Console profile and service account, I initially chose to download a P12 file instead of the recommended JSON. After beating my head against the wall because of the "GAPI: Failed to authenticate user" error, I went through the service account process again, but this time downloaded the JSON first, THEN generated a new P12 file. That seems to have done the trick, as I'm no longer getting the authentication error. Hope this is useful to someone else.
