### ISSUE TITLE
The OAuth client was not found.

### ISSUE THREAD

**Issue by stankomix** [erebusnz/gapi-google-analytics-php-interface#149]
Hi,

I fallow the your instructions and generated  p12 file and other but when call the API got the follow error:

[body] => { "error": "invalid_client", "error_description": "The OAuth client was not found." } [code] => 401

Any suggestions ?
Thanks

**Comment by erebusnz** [comment]
If you are certain that your client email (XXXXXXXX@developer.gserviceaccount.com) and p12 key is correct, then the problem is likely with your API configuration in the Google developers console.

[See relevant stackoverflow](http://stackoverflow.com/questions/17166848/invalid-client-in-google-oauth2)
